name: deployments
on:
  push:
    branches: [ production, staging, development ]

jobs:
  deployDev:
    name: 'Deploy to dev environment'
    if: github.event.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: SpicyPizza/create-envfile@v1
        with:
          directory: env
          file_name: .development.env
          envkey_ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.5.x'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --release -t lib/main.dev.dart --flavor dev
      - run: flutter build appbundle --release -t lib/main.dev.dart --flavor dev
      - uses: actions/upload-artifact@v2
        with:
          name: apk-dev-release
          path: build/app/outputs/flutter-apk/app-dev-release.apk
      - uses: actions/upload-artifact@v2
        with:
          name: aab-dev-release
          path: build/app/outputs/bundle/devRelease/app-dev-release.aab
#          path: |
#            - []
#            apk-dev-release: build/app/outputs/flutter-apk/app-dev-release.apk
#            aab-dev-release: build/app/outputs/bundle/devRelease/app-dev-release.aab
#            build/app/outputs/flutter-apk/app-dev-release.apk
#            build/app/outputs/bundle/devRelease/app-dev-release.aab

  deployStaging:
    name: 'Deploy to staging environment'
    if: github.event.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: SpicyPizza/create-envfile@v1
        with:
          directory: env
          file_name: .staging.env
          envkey_ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.5.x'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --release -t lib/main.staging.dart --flavor staging
      - run: flutter build appbundle --release -t lib/main.staging.dart --flavor staging
      - uses: actions/upload-artifact@v1
        with:
          name: apk-staging-release
          path: build/app/outputs/flutter-apk/app-staging-release.apk

  deployProd:
    name: 'Deploy to production environment'
    if: github.event.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: SpicyPizza/create-envfile@v1
        with:
          directory: env
          file_name: .production.env
          envkey_ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.5.x'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --release -t lib/main.dart --flavor prod
      - run: flutter build appbundle --release -t lib/main.dart --flavor prod
      - uses: actions/upload-artifact@v1
        with:
          name: apk-prod-release
          path: build/app/outputs/flutter-apk/app-prod-release.apk